FROM python:3.11-slim

WORKDIR /app

# Установка системных зависимостей
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Копирование requirements и установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование проекта
COPY . .

RUN python manage.py collectstatic

EXPOSE 8000

RUN chmod +x manage.py

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]